### ISSUE TITLE
Middle-click seems to happen twice if both internal and external trackpad are available

### ISSUE THREAD

**Issue by sersorrel** [rxhanson/Middle-Community#54]
Whenever I three-finger-tap on either my macbook's internal trackpad or my external magic trackpad, I seem to get two middle-click events. Primarily this manifests as things getting pasted into iTerm2 twice – if I press ⌘-V, it just pastes once, so it's definitely not that the clipboard contents are getting duplicated. This has just started happening since I bought and plugged in the magic trackpad, and if I turn the trackpad off, it stops happening.

If I open the touch viewer and tap both trackpads once so that both of them are visible, three-finger-tapping on one trackpad makes both touch viewers flash. Is that meant to happen?

"Use private framework" doesn't seem to make a difference.

**Comment by rxhanson** [comment]
Thanks for reporting and doing some initial investigation. Last I looked into this, iTerm2 has its own middle click behavior, so it's likely that this is where the conflict is. You'll likely either want to disable the iTerm2 behavior or ignore iTerm2 in Middle. 

As an aside, the touch viewers will both flash for a single middle click event. I find it's easy to test Middle using this: https://unixpapa.com/js/testmouse.html

**Comment by sersorrel** [comment]
oops, yes, I had "three-finger tap emulates middle click" enabled in iTerm2... Disabling it didn't seem to actually change anything, though; with Middle running I still get the clipboard pasted twice, and after quitting Middle, three-finger-tap still works to paste into iTerm2. Asking Middle to ignore iTerm2 works, though.

I only see one pair of mousedown/mouseup events per three-finger tap on that website, so I guess this is an iTerm2 issue, or me not understanding what "three-finger tap emulates middle click" means.

**Comment by rxhanson** [comment]
Good to know, thanks for the follow up on this. If enough people get tripped up by it, I might add something into the app to let users know of potential conflict.
