### ISSUE TITLE
Can't middle click portion on the top of screen while app is full-screen

### ISSUE THREAD

**Issue by ryanNupp** [rxhanson/Middle-Community#74]
Hello, first just wanted to say I love using this app and have been using it for years now.

Lately I have been getting an issue which I never had before. Actually I have been experiencing it for a few months now but I've been putting off typing up a bug report.

When I am in an app full-screen I cannot middle click on the top portion of the window. Almost like there is a barrier of a few pixels tall stretching across the top of the screen. This hinders something that I frequently use this app for. I like to middle click on browser tabs in Firefox and Chrome to close tabs, but the top half of tabs don't let me middle click. If I move my cursor to the bottom portion of the tab in these browsers I can middle click just fine (or anywhere else on the screen for that matter).

I suspect this bug might have something to do with how middle does not let you use the middle click function on the menu bar in desktop mode. When I am in an app full-screen I have noticed that the portion of the screen I cannot use middle click happens to be the exact same size as the menu bar. Even though the menu mar is hidden in full-screen it still blocks middle clicking in that area.

Here is some information about my machine:
<img width="392" alt="Screenshot 2024-05-22 at 3 33 23 PM" src="https://github.com/rxhanson/Middle-Community/assets/99926961/09f44dac-99ec-4342-bd90-95f748de9464">
<img width="392" alt="Screenshot 2024-05-22 at 3 33 09 PM" src="https://github.com/rxhanson/Middle-Community/assets/99926961/61721683-9988-45af-99ad-38de2362d0d8">

**Comment by rxhanson** [comment]
Thanks for reporting. I'll see what I can do for the next release.

**Comment by rxhanson** [comment]
Thanks for reporting. I'm not able to reproduce this. Do you have anything unusual about your setup, and is it only on the built-in display?

**Comment by ryanNupp** [comment]
I apologize for the extremely delayed response.

I only get this issue on my built-in display, set at the default resolution and everything. Occasionally I plug my laptop into an external 1440p monitor and use it as a second screen. The issue does not occur on the external monitor, it only happens on the built-in display.

Whether or not I am plugged into an external display the issue persists, even after rebooting.

**Comment by rxhanson** [comment]
No worries. I also have a 2020 M1 MacBook Air, and it works fine for me. To see what Middle is seeing/doing, you can go to the menu bar menu, hold the option key, and select Debug -> Show Viewer. This can be done to show the viewer window on top of a full-screen app as well. When you middle click with Middle, the viewer window will turn grey. This way, we can at least make sure that middle is telling us it is executing a middle click. There's still a possibility that something has gone awry with Middle, but want to try to narrow things down as much as possible.

**Comment by rxhanson** [comment]
Sorry for the delayed response; I've been traveling. The issue does come down to a pretty strange macOS limitation where force touching with the cursor in the top portion of the screen doesn't work. Unfortunately, I'm not aware of any way to force macOS to allow Force Touch to work here, and I'll leave this issue closed.
